import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Nav & Common
    appName: 'Where is the train',
    dashboard: 'Dashboard',
    searchTrains: 'Search Trains',
    lostFound: 'Lost & Found',
    suggestions: 'Suggestions',
    myProfile: 'My Profile',
    adminPanel: 'Admin Panel',
    signOut: 'Sign Out',
    home: 'Home',
    welcomeBack: 'Welcome Back',
    systemTitle: 'Where is the Train Tracking Platform',
    emailAddress: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    getStarted: 'Get Started',
    createAccount: 'Create Account',
    displayName: 'Display Name',
    confirmPassword: 'Confirm Password',
    hasAccount: 'Already have an account?',
    loading: 'Loading...',
    cancel: 'Cancel',
    save: 'Save',
    active: 'Active',
    resolved: 'Resolved',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    closed: 'Closed',

    // Dashboard / Home
    welcomeSub: 'Welcome to the Where Is The Train tracking hub',
    systemAboutTitle: 'Crowdsourced Real-Time Train Tracker',
    systemAboutDesc: 'WITT is a community-powered platform for commuters. Passengers share live locations, crowd density, and station delay reports, enabling everyone to trace train arrivals instantly via WebSockets and real-time updates.',
    statUsers: 'System Commuters',
    statTrains: 'Active Train Routes',
    statTrips: 'Active Trips Running Today',
    statUpdates: 'Live Updates',
    todayTrips: "Today's Active Trips",
    followedTrains: 'My Followed Trains',
    liveFeed: 'Live Updates',
    trackLive: 'Track Live',
    trackDate: 'Track Date',
    noActiveTrips: 'No trips have departed yet today.',
    noFollowedTrips: 'No followed trains. Click "Track Live" on an active trip above to follow it.',
    noUpdatesFeed: 'No updates posted today yet. Be the first to post!',
    myStatus: 'My Status',
    boarded: 'Boarded (Started)',
    completed: 'Completed (Ended)',
    following: 'Following',

    // Search Page
    searchTitle: 'Search Trains',
    searchSub: 'Find trains by number or specify origin and destination stations',
    trainNumberTab: 'Train Number',
    routeTab: 'Station Route',
    originStation: 'Origin Station',
    destinationStation: 'Destination Station',
    searchBtn: 'Search Train',
    searchResults: 'Search Results',
    noTrainsFound: 'No trains found matching search criteria.',
    noTrainSelected: 'No Train Selected',
    selectTrainTip: 'Select a search result to view its stops, timetable, and follow options.',
    timetableHeader: 'Timetable & Stations',
    activeLive: 'Active Live',
    scheduled: 'Scheduled',
    noStopsInfo: 'No stop information available for this train.',
    origin: 'Origin',
    terminal: 'Terminal',
    failedToLoadFollowers: 'Failed to load followers.',

    // Trip Details Page
    liveRouteTracking: 'Live Route Tracking',
    shareTrainUpdate: 'Share Train Update',
    send: 'Send',
    shareGps: 'Share GPS Location',
    livePassengerReports: 'Live Updates',
    noLiveReports: 'No updates reported yet for this trip. Be the first to share details!',
    followTrip: 'Follow Trip',
    unfollowTrip: 'Unfollow Trip',
    currentLastStation: 'Current/Last Station',
    gpsMapPin: 'Map Pin',
    statusTag: 'Status Tag',
    crowdLevel: 'Crowd Level',
    noStatusTag: 'No Status Tag',
    noCrowdTag: 'No Crowd Tag',
    isTripStartedQuestion: 'Is the trip started?',
    isTripStartedSub: 'The scheduled departure time has passed. Please confirm if the train has departed.',
    isTripEndedQuestion: 'Is the trip ended?',
    isTripEndedSub: 'The scheduled arrival time has passed. Please confirm if the train has arrived at its final destination.',
    yes: 'Yes',
    notYet: 'Not yet',
    
    // Status & Crowd Labels
    OnTime: 'On Time',
    Delayed: 'Delayed',
    Crowded: 'Crowded',
    Empty: 'Empty',
    Cancelled: 'Cancelled',
    AtStation: 'Arrived Station',
    EmptyChairs: 'Empty Chairs',
    FullChairs: 'Full Seats',
    AisleCrowded: 'Crowded Aisle',

    // Lost & Found
    lostFoundTitle: 'Lost & Found Community',
    lostFoundSub: 'Help fellow passengers locate items misplaced on trains',
    fileReport: 'File Report',
    lostItems: 'Lost Items',
    foundItems: 'Found Items',
    noActiveReports: 'No Active Reports',
    everythingAccounted: 'Everything is accounted for. Check back later or file a new report if you lost something.',
    reportType: 'Report Type',
    iLostItem: 'I lost an item',
    iFoundItem: 'I found an item',
    title: 'Title',
    desc: 'Detailed Description',
    walletPlaceholder: 'e.g. Lost Black Leather Wallet',
    descPlaceholder: 'Describe colors, logos, location, or stations...',
    trainNoOpt: 'Train Number (Optional)',
    contactInfoOpt: 'Contact Info (Optional)',
    imageUrlOpt: 'Image URL (Optional)',
    submitReport: 'Submit Report',
    comments: 'Comments',
    askQuestion: 'Ask a question or offer help...',
    resolvedBanner: 'This report has been marked resolved. Comments are closed.',
    markAsResolved: 'Mark as Resolved',

    // Suggestions Page
    suggestionsSub: 'Propose new train details or correct timetables for moderator review',
    submitSuggestion: 'Submit Route Suggestion',
    trainNameEn: 'Train Name (English)',
    trainNameAr: 'Train Name (Arabic)',
    descEn: 'Description (English)',
    descAr: 'Description (Arabic)',
    routeEn: 'Route & Stops (English)',
    routeAr: 'Route & Stops (Arabic)',
    myProposalLog: 'My Proposal Log',
    noSuggestionsYet: 'You have not submitted any route suggestions yet.',
    adminNotes: 'Admin Notes',

    // Profile Page
    profileSub: 'Manage your personal details and view your travel tracking history',
    accountInfo: 'Account Information',
    editAvatar: 'Edit Profile Picture',
    uploadPhoto: 'Upload Photo',
    removePhoto: 'Remove Photo',
    chooseFile: 'Choose Image File',
    bioPlaceholder: 'Tell us about yourself...',
    saveProfile: 'Save Profile Details',
    travelLog: 'Travel Tracking Log',
    noHistoryYet: 'No history found. Trains you follow and track will appear here.',
    
    // Train Follow Plan
    follow: 'Follow',
    editPlan: 'Edit Plan',
    unfollowPlan: 'Unfollow Train',
    followPlanTitle: 'Configure Train Follow Plan',
    frequency: 'Frequency',
    roleType: 'Role Type',
    targetStation: 'Target Station',
    alertTiming: 'Alert Lead Time',
    alertTimingLabel: 'Alert Lead Time (minutes prior to stop)',
    passenger: 'Passenger',
    follower: 'Follower',
    upcomingTripsHeader: 'Next 24 Hours (Immediate Trips)',
    followedTrainsHeader: 'All Followed Trains (Recurring Plans)',
    noUpcomingTrips: 'No upcoming trip instances scheduled within the next 24 hours.',
    noFollowedPlans: 'You are not currently subscribed to any recurring train follow plans.',
    unfollowTripConfirm: 'Are you sure you want to unfollow this trip? This bypasses only this specific journey.',
    unfollowPlanConfirm: 'Are you sure you want to cancel the recurring follow plan for this train? This will cancel all future, upcoming trips.',
    saveFollowPlan: 'Save Configuration',
    upcomingTripsInfo: 'Manage immediate trip instances for the next 24 hours. Opt out of individual trips without affecting your overall recurring plan.',
    daysOfWeekSelect: 'Days of Week',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    planSaved: 'Follow plan saved successfully!',
    planDeleted: 'Follow plan cancelled successfully!',
    unfollowedTripSuccess: 'Unfollowed this specific trip successfully!',

    // Admin Page
    adminSub: 'Manage database metadata, disruptions, user moderation, and bulk imports',
    users: 'Users',
    routeSuggestions: 'Route Suggestions',
    serviceAlerts: 'Service Alerts',
    bulkImportCsv: 'Bulk Import CSV',
    closeAd: 'Close Ad',
    skipIn: 'Skip in {seconds}s',
    tableName: 'Name',
    tableEmail: 'Email',
    tableRole: 'Role',
    tableStatus: 'Status',
    tableActions: 'Actions',
    suspend: 'Suspend',
    unsuspend: 'Unsuspend',
    changeRole: 'Change Role',
    review: 'Review',
    noPendingSug: 'No pending route suggestions.',
    reviewSugTitle: 'Review Suggestion',
    decisionNotes: 'Moderator Decision Notes',
    reject: 'Reject',
    approve: 'Approve',
    activeDisruptions: 'Active Disruption Alerts',
    createServiceAlert: 'Create Service Alert',
    affectedLineOpt: 'Affected Line/Train (Optional)',
    postAlert: 'Post Alert',
    deactivate: 'Deactivate',
    deactivated: 'Deactivated',
    importStops: 'Bulk Import Stops',
    importTrains: 'Bulk Import Trains',
    stopsCsvColumns: 'Expected columns: Code,NameAr,NameEn,CityAr,CityEn,Latitude,Longitude,DescriptionAr,DescriptionEn',
    trainsCsvColumns: 'Expected columns: TrainNumber,NameAr,NameEn,DescAr,DescEn,StopCode,StopOrder,Arrival,Departure',
    parseStopsBtn: 'Upload & Parse Stops',
    parseTrainsBtn: 'Upload & Parse Trains',
    askToRemove: 'Ask to Remove',
    removalPending: 'Removal Pending',
    confirmRemoval: 'Confirm Removal',
    denyRemoval: 'Deny Removal',
    liveUpdatesModeration: 'Live Updates Moderation',
    pendingApproval: 'Pending Approval',
    removalRequests: 'Removal Requests',
    noPendingUpdates: 'No pending updates awaiting approval.',
    trains: 'Trains',
    trips: 'Trips',
    stops: 'Stops',
    lookups: 'Lookups',
    railwayPaths: 'Railway Paths',
    systemSettings: 'System Settings',
    adminsRoles: 'Admins & Roles',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications yet',
    clearOldTripsData: 'Clear Old Trips Data',
    clearTripData: 'Clear Trip Data',
    scheduleTrip: 'Schedule Trip',
    searchTripsPlaceholder: 'Search trips by train number or date...',
    trainNo: 'Train No',
    trainName: 'Train Name',
    date: 'Date',
    followers: 'Followers',
    status: 'Status',
    actions: 'Actions',
    noTripsFound: 'No trips found.',
    confirmDeleteTrip: 'Are you sure you want to delete this trip?',
    confirmClearOldTrips: 'Are you sure you want to clear all progress (telemetry) data for all ended and cancelled trips? This action is permanent and saves database storage.',
    confirmClearTrip: 'Are you sure you want to clear the progress (telemetry) data for Train #{trainNumber} on {tripDate}? This action is permanent.',
    tripCreatedSuccess: 'Trip created successfully.',
    tripDeletedSuccess: 'Trip deleted successfully.',
    tripTelemetryClearedSuccess: 'Successfully cleared telemetry data for Train #{trainNumber} on {tripDate}.',
    scheduleNewTrip: 'Schedule New Trip',
    trainSelect: 'Train *',
    selectTrainOption: '-- Select Train --',
    tripDateLabel: 'Trip Date *',
    systemAdmins: 'System Admins',
    customRoles: 'Custom Roles',
    searchPlaceholder: 'Search {item}...',
    addAdmin: 'Add Admin',
    addCustomRole: 'Add Custom Role',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    editRole: 'Edit Role',
    editAdminDetails: 'Edit Admin Details',
    addSystemAdmin: 'Add System Admin',
    roleNameLabel: 'Role Name *',
    modulePermissions: 'Module Permissions',
    module: 'Module',
    view: 'View',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    saveChanges: 'Save Changes',
    createRole: 'Create Role',
    createAdmin: 'Create Admin',
    displayNameLabel: 'Display Name *',
    emailLabel: 'Email *',
    passwordLabel: 'Password',
    assignRoleLabel: 'Assign Role *',
    selectCustomRoleOption: '-- Select custom role --',
    confirmDeleteRole: 'Are you sure you want to delete this role?',
    confirmDeleteAdmin: 'Are you sure you want to delete this admin?',
    roleUpdatedSuccess: 'Role updated successfully.',
    roleCreatedSuccess: 'Role created successfully.',
    adminUpdatedSuccess: 'Admin updated successfully.',
    adminCreatedSuccess: 'Admin created successfully.',
    roleDeletedSuccess: 'Role deleted successfully.',
    adminDeletedSuccess: 'Admin deleted successfully.',
    noAdminsFound: 'No admins found.',
    noCustomRolesFound: 'No custom roles found.',
    clearProgressData: 'Clear progress data',
    confirmClearProgressData: 'Are you sure you want to clear all progress (telemetry) data for this trip? This action is permanent and saves database storage.',
    tripProgressClearedSuccess: 'Successfully cleared telemetry data for this trip.',
    turnOffNotifications: 'Turn Off Notifications',
    turnOnNotifications: 'Turn On Notifications',
    recenter: 'Re-center',
    speedometer: 'Speed',
    upcomingStopsCount: 'Stops Remaining',
    liveGpsSnappingActive: 'Live Snapped Tracking Active',
    passengerModeTitle: 'Passenger Mode (Share GPS)',
    passengerModeSub: 'Broadcast your location to improve live ETA snapping for all users.',
    stopsSequence: 'Stops Sequence',
    editTrain: 'Edit Train',
    profileUpdatedSuccess: 'Profile updated successfully!',
    failedToUploadPhoto: 'Failed to upload photo.',
    failedToRemovePhoto: 'Failed to remove photo.',
    uploading: 'Uploading...',
    confirmRequestRemoval: 'Are you sure you want to request removal of this update?',
    whatIsHappening: 'What is happening?',
    latestTrips: 'Latest Trips',
    dateFrom: 'Date From',
    dateTo: 'Date To',
    noTripsScheduled: 'No trips scheduled.',
    prev: 'Prev',
    next: 'Next',
    station: 'Station',
    bypass: 'Bypass',
    followedTrainsSub: 'Manage your recurring schedules and automatic follow plans.',
    failedToUnfollowTrip: 'Failed to unfollow trip.',
    failedToCancelFollowPlan: 'Failed to cancel follow plan.',
    failedToUpdateProfile: 'Failed to update profile.',
    failedToSaveFollowPlan: 'Failed to save follow plan.',
    pleaseEnableFollowOneDay: 'Please enable follow configuration for at least one day.',
    pleaseSelectTargetStationAllDays: 'Please select a target station for all enabled days.',
    backToSearch: 'Back to Search',
    geolocationNotSupported: 'Geolocation is not supported by your browser.',
    locationSharingFailedCoords: 'Location sharing enabled but failed to get coordinates. Submitting update without coordinates.',
    geolocationNotSupportedSubmitting: 'Geolocation not supported in browser. Submitting without coordinates.',
    searchStops: 'Search stops...',
    importCsv: 'Import CSV',
    processing: 'Processing...',
    addStop: 'Add Stop',
    noStopsFound: 'No stops found.',
    code: 'Code',
    city: 'City',
    paths: 'Paths',
    coords: 'Coords',
    addNewStop: 'Add New Stop',
    stationCode: 'Station Code',
    latitude: 'Latitude',
    longitude: 'Longitude',
    railwayPaths: 'Railway Paths',
    nameEnLabel: 'Name (En) *',
    nameArLabel: 'Name (Ar) *',
    stationCodeLabel: 'Station Code *',
    cityLabel: 'City',
    latitudeLabel: 'Latitude *',
    longitudeLabel: 'Longitude *',
    descEnLabel: 'Description (En)',
    descArLabel: 'Description (Ar)',
    createStop: 'Create Stop',
    deleteStopConfirm: 'Are you sure you want to delete this stop?',
    stopDeletedSuccess: 'Stop deleted successfully.',
    stopCreatedSuccess: 'Stop created successfully.',
    csvEmptyOrInvalid: 'CSV is empty or invalid.',
    failedToReadFromFile: 'Failed to read file: ',
    importSuccessful: 'Imported successfully!',
    csvAnalysisResult: 'CSV Analysis Result',
    csvAnalysisIntro: 'We analyzed the file {fileName} containing {total} valid row(s).',
    newRecords: 'New Records:',
    duplicateRecords: 'Duplicate Records (Existing Code):',
    duplicatesFoundAction: 'Duplicates found. How would you like to handle them?',
    overwriteExisting: 'Overwrite Existing',
    ignoreDuplicates: 'Ignore Duplicates',
    everythingLooksOkNoDuplicates: 'Everything looks OK. No duplicates found. You can safely proceed to insert.',
    confirmAndInsert: 'Confirm & Insert',
    stopDetails: 'Stop Details',
    noDescriptionAvailable: 'No description available',
    editStop: 'Edit Stop',
    viewDetailsAndMap: 'View Details & Map'
  },
  ar: {
    // Nav & Common
    appName: 'القطر وصل فين',
    dashboard: 'لوحة التحكم',
    searchTrains: 'البحث عن قطار',
    lostFound: 'المفقودات والمعثورات',
    suggestions: 'الاقتراحات',
    myProfile: 'ملفي الشخصي',
    adminPanel: 'لوحة الإدارة',
    signOut: 'تسجيل الخروج',
    home: 'الرئيسية',
    welcomeBack: 'مرحباً بعودتك',
    systemTitle: 'منصة تتبع ورصد حركة القطارات',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    signIn: 'تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟',
    createOne: 'أنشئ حساباً جديداً',
    getStarted: 'ابدأ الآن',
    createAccount: 'إنشاء الحساب',
    displayName: 'الاسم المستعار',
    confirmPassword: 'تأكيد كلمة المرور',
    hasAccount: 'لديك حساب بالفعل؟',
    loading: 'جاري التحميل...',
    cancel: 'إلغاء',
    save: 'حفظ',
    active: 'نشط',
    resolved: 'تم الحل',
    pending: 'قيد الانتظار',
    approved: 'مقبول',
    rejected: 'مرفوض',
    closed: 'مغلق',

    // Dashboard / Home
    welcomeSub: 'أهلاً بك في منصة رصد وتتبع حركة القطارات اليومية',
    systemAboutTitle: 'رصد تشاركي فوري لمواقع القطارات',
    systemAboutDesc: 'منصة تتبع القطارات تعتمد على جهود الركاب والمسافرين لمشاركة التحديثات المباشرة. يشارك الركاب مواقعهم، ومستوى الازدحام، والتأخيرات في المحطات، مما يسمح للجميع بمتابعة مواعيد الوصول فوراً.',
    statUsers: 'المستخدمين النشطين',
    statTrains: 'خطوط القطارات النشطة',
    statTrips: 'رحلات القطارات اليوم',
    statUpdates: 'التحديثات المباشرة',
    todayTrips: 'الرحلات النشطة اليوم',
    followedTrains: 'قطاراتي المتابعة',
    liveFeed: 'التحديثات المباشرة',
    trackLive: 'تتبع الآن',
    trackDate: 'تاريخ الرحلة',
    noActiveTrips: 'لا توجد رحلات منطلقة اليوم بعد.',
    noFollowedTrips: 'لا توجد قطارات متابعة. اضغط "تتبع الآن" على أحد قطارات اليوم لمتابعته.',
    noUpdatesFeed: 'لا توجد تحديثات من الركاب اليوم بعد. كن أول من ينشر تحديثاً!',
    myStatus: 'حالتـي',
    boarded: 'ركبت القطار (بدأت الرحلة)',
    completed: 'وصلت الوجهة (انتهت)',
    following: 'متابع',

    // Search Page
    searchTitle: 'البحث عن قطار',
    searchSub: 'ابحث برقم القطار مباشرة أو حدد محطة القيام ومحطة الوصول',
    trainNumberTab: 'رقم القطار',
    routeTab: 'مسار المحطات',
    originStation: 'محطة القيام',
    destinationStation: 'محطة الوصول',
    searchBtn: 'بحث عن القطار',
    searchResults: 'نتائج البحث',
    noTrainsFound: 'لم يتم العثور على قطارات تطابق معايير البحث.',
    noTrainSelected: 'لم يتم اختيار أي قطار',
    selectTrainTip: 'اختر قطاراً من قائمة نتائج البحث لعرض المحطات وجدول المواعيد وخيارات التتبع.',
    timetableHeader: 'جدول المواعيد والمحطات',
    activeLive: 'مباشر الآن',
    scheduled: 'مجدول',
    noStopsInfo: 'لا توجد معلومات محطات متاحة لهذا القطار.',
    origin: 'بداية الخط',
    terminal: 'نهاية الخط',
    failedToLoadFollowers: 'فشل في تحميل المتابعين.',

    // Trip Details Page
    liveRouteTracking: 'التتبع المباشر لخط السير',
    shareTrainUpdate: 'مشاركة تحديث عن القطار',
    send: 'إرسال',
    shareGps: 'مشاركة موقعي الجغرافي (GPS)',
    livePassengerReports: 'التحديثات المباشرة',
    noLiveReports: 'لا توجد بلاغات تتبع بعد لهذه الرحلة. شارك الركاب الموقف الآن!',
    followTrip: 'متابعة الرحلة',
    unfollowTrip: 'إلغاء المتابعة',
    currentLastStation: 'المحطة الحالية/الأخيرة',
    gpsMapPin: 'خريطة',
    statusTag: 'حالة القطار',
    crowdLevel: 'مستوى الازدحام',
    noStatusTag: 'بدون تحديد حالة',
    noCrowdTag: 'بدون تحديد ازدحام',
    isTripStartedQuestion: 'هل بدأت الرحلة؟',
    isTripStartedSub: 'لقد مر وقت المغادرة المجدول. يرجى تأكيد ما إذا كان القطار قد تحرك.',
    isTripEndedQuestion: 'هل انتهت الرحلة؟',
    isTripEndedSub: 'لقد مر وقت الوصول المجدول. يرجى تأكيد ما إذا كان القطار قد وصل إلى وجهته النهائية.',
    yes: 'نعم',
    notYet: 'ليس بعد',
    
    // Status & Crowd Labels
    OnTime: 'في الموعد',
    Delayed: 'متأخر',
    Crowded: 'مزدحم جداً',
    Empty: 'شبه فارغ',
    Cancelled: 'ملغي',
    AtStation: 'وصل المحطة',
    EmptyChairs: 'مقاعد فارغة',
    FullChairs: 'جميع المقاعد ممتلئة',
    AisleCrowded: 'الممر مزدحم للغاية',

    // Lost & Found
    lostFoundTitle: 'المفقودات والمعثورات',
    lostFoundSub: 'ساعد الركاب والمسافرين في العثور على متعلقاتهم المفقودة داخل القطارات',
    fileReport: 'إرسال بلاغ',
    lostItems: 'مفقودات',
    foundItems: 'معثورات',
    noActiveReports: 'لا توجد بلاغات نشطة',
    everythingAccounted: 'تم العثور على كل شيء. تفقد الصفحة لاحقاً أو أرسل بلاغاً جديداً إذا فقدت شيئاً.',
    reportType: 'نوع البلاغ',
    iLostItem: 'فقدت غرضاً',
    iFoundItem: 'عثرت على غرض',
    title: 'عنوان البلاغ',
    desc: 'الوصف التفصيلي',
    walletPlaceholder: 'مثال: فقدت محفظة جلد سوداء',
    descPlaceholder: 'صف الألوان، العلامات التجارية، مكان الفقد، أو المحطات...',
    trainNoOpt: 'رقم القطار (اختياري)',
    contactInfoOpt: 'رقم التواصل (اختياري)',
    imageUrlOpt: 'رابط صورة الغرض (اختياري)',
    submitReport: 'إرسال البلاغ',
    comments: 'التعليقات',
    askQuestion: 'اكتب سؤالاً أو اعرض مساعدة للتوصل للغرض...',
    resolvedBanner: 'تم حل هذا البلاغ وإغلاق التعليقات.',
    markAsResolved: 'تعليم كتم الحل',

    // Suggestions Page
    suggestionsSub: 'اقترح تعديلات على تفاصيل القطار أو مواعيد المحطات لمراجعتها من قبل المشرفين',
    submitSuggestion: 'تقديم اقتراح مسار جديد',
    trainNameEn: 'اسم القطار (بالأنجليزية)',
    trainNameAr: 'اسم القطار (بالعربية)',
    descEn: 'الوصف (بالأنجليزية)',
    descAr: 'الوصف (بالعربية)',
    routeEn: 'تفاصيل المسار والمحطات (بالأنجليزية)',
    routeAr: 'تفاصيل المسار والمحطات (بالعربية)',
    myProposalLog: 'سجل المقترحات الخاصة بي',
    noSuggestionsYet: 'لم تقم بتقديم أي مقترحات لمسارات بعد.',
    adminNotes: 'ملاحظات الإدارة',

    // Profile Page
    profileSub: 'إدارة بياناتك الشخصية ومراجعة سجل التتبع والرحلات الخاصة بك',
    accountInfo: 'معلومات الحساب',
    editAvatar: 'تعديل الصورة الشخصية',
    uploadPhoto: 'رفع صورة',
    removePhoto: 'إزالة الصورة',
    chooseFile: 'اختر ملف الصورة',
    bioPlaceholder: 'اكتب نبذة قصيرة عن نفسك...',
    saveProfile: 'حفظ التعديلات',
    travelLog: 'سجل السفر والرحلات',
    noHistoryYet: 'السجل فارغ. القطارات التي تتابعها وتتتبعها ستظهر هنا.',
    
    // Train Follow Plan
    follow: 'متابعة',
    editPlan: 'تعديل الخطة',
    unfollowPlan: 'إلغاء متابعة القطار',
    followPlanTitle: 'تهيئة خطة متابعة القطار',
    frequency: 'التكرار',
    roleType: 'نوع الدور',
    targetStation: 'المحطة المستهدفة',
    alertTiming: 'توقيت التنبيه',
    alertTimingLabel: 'توقيت التنبيه (الدقائق قبل التوقف)',
    passenger: 'راكب',
    follower: 'متابع',
    upcomingTripsHeader: 'الـ 24 ساعة القادمة (رحلات فورية)',
    followedTrainsHeader: 'جميع القطارات المتابعة (الخطط المتكررة)',
    noUpcomingTrips: 'لا توجد رحلات قادمة مجدولة خلال الـ 24 ساعة القادمة.',
    noFollowedPlans: 'أنت غير مشترك في أي خطط تتبع متكررة للقطارات حالياً.',
    unfollowTripConfirm: 'هل أنت متأكد من إلغاء متابعة هذه الرحلة المحددة؟ هذا سيتجاوز هذه الرحلة فقط دون إلغاء الخطة المتكررة.',
    unfollowPlanConfirm: 'هل أنت متأكد من إلغاء خطة المتابعة المتكررة لهذا القطار؟ سيؤدي ذلك لإلغاء متابعة جميع الرحلات المستقبلية.',
    saveFollowPlan: 'حفظ التهيئة',
    upcomingTripsInfo: 'إدارة الرحلات الفورية للـ 24 ساعة القادمة. يمكنك إلغاء رحلات فردية دون التأثير على خطة المتابعة العامة.',
    daysOfWeekSelect: 'أيام الأسبوع',
    sunday: 'الأحد',
    monday: 'الإثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    planSaved: 'تم حفظ خطة المتابعة بنجاح!',
    planDeleted: 'تم إلغاء خطة المتابعة بنجاح!',
    unfollowedTripSuccess: 'تم إلغاء متابعة هذه الرحلة المحددة بنجاح!',

    // Admin Page
    adminSub: 'لوحة الإدارة لإضافة البيانات الأساسية، التنبيهات، تعديل حسابات المستخدمين والاستيراد الجماعي',
    users: 'المستخدمين',
    routeSuggestions: 'اقتراحات المسارات',
    serviceAlerts: 'تنبيهات الخدمة',
    bulkImportCsv: 'استيراد جماعي CSV',
    closeAd: 'إغلاق الإعلان',
    skipIn: 'تخطي بعد {seconds} ثوانٍ',
    tableName: 'الاسم',
    tableEmail: 'البريد الإلكتروني',
    tableRole: 'الصلاحية',
    tableStatus: 'الحالة',
    tableActions: 'الإجراءات',
    suspend: 'حظر',
    unsuspend: 'فك الحظر',
    changeRole: 'تغيير الصلاحية',
    review: 'مراجعة الاقتراح',
    noPendingSug: 'لا توجد اقتراحات مسارات قيد المراجعة حالياً.',
    reviewSugTitle: 'مراجعة تفاصيل الاقتراح',
    decisionNotes: 'ملاحظات قرار المراجعة والاعتماد',
    reject: 'رفض الاقتراح',
    approve: 'قبول وتثبيت المسار',
    activeDisruptions: 'تنبيهات التأخيرات النشطة',
    createServiceAlert: 'إنشاء تنبيه خدمة جديد',
    affectedLineOpt: 'الخط أو القطار المتأثر (اختياري)',
    postAlert: 'نشر التنبيه',
    deactivate: 'إلغاء التفعيل',
    deactivated: 'ملغي التفعيل',
    importStops: 'استيراد جماعي للمحطات',
    importTrains: 'استيراد جماعي للقطارات والمواعيد',
    stopsCsvColumns: 'الترتيب المتوقع للأعمدة: Code,NameAr,NameEn,CityAr,CityEn,Latitude,Longitude,DescriptionAr,DescriptionEn',
    trainsCsvColumns: 'الترتيب المتوقع للأعمدة: TrainNumber,NameAr,NameEn,DescAr,DescEn,StopCode,StopOrder,Arrival,Departure',
    parseStopsBtn: 'رفع وتحليل ملف المحطات',
    parseTrainsBtn: 'رفع وتحليل ملف القطارات والمواعيد',
    askToRemove: 'طلب حذف التحديث',
    removalPending: 'قيد انتظار الحذف',
    confirmRemoval: 'تأكيد الحذف',
    denyRemoval: 'رفض الحذف',
    liveUpdatesModeration: 'إدارة التحديثات المباشرة',
    pendingApproval: 'في انتظار الموافقة',
    removalRequests: 'طلبات الحذف',
    noPendingUpdates: 'لا توجد تحديثات معلقة في انتظار الموافقة.',
    trains: 'القطارات',
    trips: 'الرحلات اليومية',
    stops: 'المحطات',
    lookups: 'الجداول المرجعية',
    railwayPaths: 'مسارات السكك الحديدية',
    systemSettings: 'إعدادات النظام',
    adminsRoles: 'المشرفون والصلاحيات',
    notifications: 'التنبيهات',
    markAllRead: 'تعليم الكل كمقروء',
    noNotifications: 'لا توجد تنبيهات بعد',
    clearOldTripsData: 'مسح بيانات الرحلات القديمة',
    clearTripData: 'مسح بيانات الرحلة',
    scheduleTrip: 'جدولة رحلة',
    searchTripsPlaceholder: 'البحث بالرقم أو التاريخ...',
    trainNo: 'رقم القطار',
    trainName: 'اسم القطار',
    date: 'التاريخ',
    followers: 'المتابعين',
    status: 'الحالة',
    actions: 'الإجراءات',
    noTripsFound: 'لم يتم العثور على رحلات.',
    confirmDeleteTrip: 'هل أنت متأكد من حذف هذه الرحلة؟',
    confirmClearOldTrips: 'هل أنت متأكد من مسح جميع بيانات التتبع للرحلات المنتهية والملغاة؟ هذا الإجراء نهائي ولا يمكن التراجع عنه لتوفير مساحة التخزين.',
    confirmClearTrip: 'هل أنت متأكد من مسح بيانات التتبع للقطار رقم {trainNumber} في تاريخ {tripDate}؟ هذا الإجراء نهائي.',
    tripCreatedSuccess: 'تم جدولة الرحلة بنجاح.',
    tripDeletedSuccess: 'تم حذف الرحلة بنجاح.',
    tripTelemetryClearedSuccess: 'تم مسح بيانات التتبع للقطار رقم {trainNumber} في تاريخ {tripDate} بنجاح.',
    scheduleNewTrip: 'جدولة رحلة جديدة',
    trainSelect: 'القطار *',
    selectTrainOption: '-- اختر القطار --',
    tripDateLabel: 'تاريخ الرحلة *',
    systemAdmins: 'مسؤولو النظام',
    customRoles: 'الأدوار والصلاحيات المخصصة',
    searchPlaceholder: 'بحث في {item}...',
    addAdmin: 'إضافة مسؤول',
    addCustomRole: 'إضافة صلاحية مخصصة',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    editRole: 'تعديل الصلاحية',
    editAdminDetails: 'تعديل بيانات المسؤول',
    addSystemAdmin: 'إضافة مسؤول نظام',
    roleNameLabel: 'اسم الصلاحية *',
    modulePermissions: 'صلاحيات الأقسام',
    module: 'القسم',
    view: 'عرض',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    saveChanges: 'حفظ التغييرات',
    createRole: 'إنشاء الصلاحية',
    createAdmin: 'إنشاء حساب المسؤول',
    displayNameLabel: 'الاسم المعروض *',
    emailLabel: 'البريد الإلكتروني *',
    passwordLabel: 'كلمة المرور',
    assignRoleLabel: 'تعيين صلاحية *',
    selectCustomRoleOption: '-- اختر الصلاحية المخصصة --',
    confirmDeleteRole: 'هل أنت متأكد من حذف هذه الصلاحية؟',
    confirmDeleteAdmin: 'هل أنت متأكد من حذف هذا المسؤول؟',
    roleUpdatedSuccess: 'تم تحديث الصلاحية بنجاح.',
    roleCreatedSuccess: 'تم إنشاء الصلاحية بنجاح.',
    adminUpdatedSuccess: 'تم تحديث المسؤول بنجاح.',
    adminCreatedSuccess: 'تم إنشاء حساب المسؤول بنجاح.',
    roleDeletedSuccess: 'تم حذف الصلاحية بنجاح.',
    adminDeletedSuccess: 'تم حذف المسؤول بنجاح.',
    noAdminsFound: 'لم يتم العثور على مسؤولين.',
    noCustomRolesFound: 'لم يتم العثور على صلاحيات مخصصة.',
    clearProgressData: 'مسح بيانات الرحلة',
    confirmClearProgressData: 'هل أنت متأكد من مسح جميع بيانات تتبع مسار هذه الرحلة؟ هذا الإجراء نهائي ولا يمكن التراجع عنه لتوفير مساحة التخزين.',
    tripProgressClearedSuccess: 'تم مسح بيانات التتبع بنجاح لهذه الرحلة.',
    turnOffNotifications: 'إيقاف التنبيهات',
    turnOnNotifications: 'تفعيل التنبيهات',
    recenter: 'إعادة توسيط',
    speedometer: 'السرعة',
    upcomingStopsCount: 'المحطات المتبقية',
    liveGpsSnappingActive: 'التتبع الفوري المفعل',
    passengerModeTitle: 'وضع الراكب (مشاركة الموقع)',
    passengerModeSub: 'شارك موقعك الجغرافي لتحسين حساب مواعيد الوصول الفورية لجميع المستخدمين.',
    stopsSequence: 'ترتيب المحطات',
    editTrain: 'تعديل القطار',
    profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح!',
    failedToUploadPhoto: 'فشل في رفع الصورة الشخصية.',
    failedToRemovePhoto: 'فشل في إزالة الصورة الشخصية.',
    uploading: 'جاري الرفع...',
    confirmRequestRemoval: 'هل أنت متأكد من طلب حذف هذا التحديث؟',
    whatIsHappening: 'ما الذي يحدث داخل القطار حالياً؟',
    latestTrips: 'الرحلات الأخيرة',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    noTripsScheduled: 'لا توجد رحلات مجدولة.',
    prev: 'السابق',
    next: 'التالي',
    station: 'المحطة',
    bypass: 'تخطي',
    followedTrainsSub: 'القطارات والمواعيد التي تتابعها بشكل متكرر وتلقائي.',
    failedToUnfollowTrip: 'فشل في إلغاء متابعة الرحلة.',
    failedToCancelFollowPlan: 'فشل في إلغاء خطة المتابعة.',
    failedToUpdateProfile: 'فشل في تحديث الملف الشخصي.',
    failedToSaveFollowPlan: 'فشل في حفظ خطة المتابعة.',
    pleaseEnableFollowOneDay: 'برجاء تفعيل المتابعة ليوم واحد على الأقل.',
    pleaseSelectTargetStationAllDays: 'برجاء اختيار محطة التنبيه لجميع الأيام المفعلة.',
    backToSearch: 'العودة للبحث',
    geolocationNotSupported: 'تحديد الموقع الجغرافي غير مدعوم في متصفحك.',
    locationSharingFailedCoords: 'تم تفعيل مشاركة الموقع ولكن فشل الحصول على الإحداثيات. يتم الإرسال بدونها.',
    geolocationNotSupportedSubmitting: 'تحديد الموقع غير مدعوم في المتصفح. يتم الإرسال بدون إحداثيات.',
    searchStops: 'البحث عن محطات...',
    importCsv: 'استيراد CSV',
    processing: 'جاري المعالجة...',
    addStop: 'إضافة محطة',
    noStopsFound: 'لم يتم العثور على محطات.',
    code: 'الرمز',
    city: 'المدينة',
    paths: 'المسارات',
    coords: 'الإحداثيات',
    addNewStop: 'إضافة محطة جديدة',
    stationCode: 'رمز المحطة',
    latitude: 'خط العرض',
    longitude: 'خط الطول',
    railwayPaths: 'مسارات السكك الحديدية',
    nameEnLabel: 'الاسم (En) *',
    nameArLabel: 'الاسم (Ar) *',
    stationCodeLabel: 'رمز المحطة *',
    cityLabel: 'المدينة',
    latitudeLabel: 'خط العرض *',
    longitudeLabel: 'خط الطول *',
    descEnLabel: 'الوصف (En)',
    descArLabel: 'الوصف (Ar)',
    createStop: 'إنشاء المحطة',
    deleteStopConfirm: 'هل أنت متأكد من حذف هذه المحطة؟',
    stopDeletedSuccess: 'تم حذف المحطة بنجاح.',
    stopCreatedSuccess: 'تم إنشاء المحطة بنجاح.',
    csvEmptyOrInvalid: 'ملف CSV فارغ أو غير صالح.',
    failedToReadFromFile: 'فشل في قراءة الملف: ',
    importSuccessful: 'تم الاستيراد بنجاح!',
    csvAnalysisResult: 'نتائج تحليل ملف CSV',
    csvAnalysisIntro: 'تم تحليل الملف {fileName} ويحتوي على {total} من الصفوف الصالحة.',
    newRecords: 'سجلات جديدة:',
    duplicateRecords: 'سجلات مكررة (رمز موجود بالفعل):',
    duplicatesFoundAction: 'تم العثور على سجلات مكررة. كيف ترغب في التعامل معها؟',
    overwriteExisting: 'تحديث السجلات الحالية',
    ignoreDuplicates: 'تجاهل المكرر',
    everythingLooksOkNoDuplicates: 'كل شيء يبدو جيداً. لم يتم العثور على سجلات مكررة. يمكنك إدراج البيانات بأمان.',
    confirmAndInsert: 'تأكيد وإدراج البيانات',
    stopDetails: 'تفاصيل المحطة',
    noDescriptionAvailable: 'لا يوجد وصف متاح',
    editStop: 'تعديل المحطة',
    viewDetailsAndMap: 'عرض التفاصيل والخريطة'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'; // Default language is English
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language, isRTL]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // Fallback to English if not found
    if (translations['en'][key]) {
      return translations['en'][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
